wandb_version: 1

q_table_filename:
  desc: null
  value: q_table.npy
cell_size:
  desc: null
  value: 300
env_width:
  desc: null
  value: 3
env_length:
  desc: null
  value: 3
env_n_agents:
  desc: null
  value: 2
env_n_pickers:
  desc: null
  value: 1
env_n_objects:
  desc: null
  value: 1
env_enable_rendering:
  desc: null
  value: false
train_episodes:
  desc: null
  value: 200000
max_steps_per_episode:
  desc: null
  value: 50
discount_factor:
  desc: null
  value: 0.9
min_exploration:
  desc: null
  value: 0.02
exploration_rate:
  desc: null
  value: 1.0
exploration_decay:
  desc: null
  value: 0.99
min_learning_rate:
  desc: null
  value: 0.01
learning_rate:
  desc: null
  value: 0.1
learning_rate_decay:
  desc: null
  value: 0.995
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.9
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694857145.404618
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 4
      - 13
      - 16
      - 23
      - 42
      4: 3.9.12
      5: 0.15.9
      8:
      - 5
